### ISSUE TITLE
Complete conversion of all objects and levels to Strict Mode.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#103]
Strict mode tends to crash the game very frequently at the moment as our non-strict objects violate it.

**Comment by rkettering** [comment]
Some HUD stuff should be the only real remaining part of this.  There's an option we've put into frogatto's module.cfg which - if you uncomment it, will let us actually fully activate "strict mode for everything", and will catch whatever's not yet been converted.

I think that getting this wrapped up before version 4 is totally realistic.

**Comment by DDR0** [comment]
We're currently failing on 
```
Unknown symbol 'solid_area' in obj frogatto_playable.bubble_shot At modules/frogatto/data/object_prototypes/base/shot.cfg 50:
bool :: (me.solid_area != null)
            ^---------^
```
I think that the HUD stuff should be mostly OK for strict mode. The new inventory screen is iirc entirely strict, now, as are the mana, ability, and heart huds.

**Comment by rkettering** [comment]
It is done.  913905213286e5d140770a5bc2d72a6d4c88f848

:whale:    :rowboat::rowboat::dash::ship:
