### ISSUE TITLE
Missing textures in pandora version

### ISSUE THREAD

**Issue by ivanovic** [frogatto/frogatto#113]
When running the Pandora version (1.3_stable built with Makefile.pandora) some of the textures are missing. This especially effects textures which belong to the level surroundings like "Wall" textures. It usually happens in the lower parts of the screen. Sometimes instead of the textures a blue square with a red X is show. The lot output appears to be normal. I can easily reproduce this with a save starting in the 2nd part of the village (after the initially locked gate) and then moving back to the left into the first village part. This is where I created the screenshot:
![frogatto_missing_textures](https://f.cloud.github.com/assets/1259950/2180128/851b898c-96fa-11e3-9f9d-8520334574ee.png)

This issue might be specific to the graphics chip/driver used in the Pandora or to some of the hacks applied. I have not been able to compile the "anura" engine version so far so I can't tell if the issue appears there, too. It would be great if someone can help me find the reason for the issue.

Paste of the log output:

pandora:~$ tail -f /media/8GB_PROGS/pandora/appdata/frogatto/app-output.txt 
CREATE OBJ: fern_foreground5
CREATE OBJ: rock_foreground_cubic3
LOADTEXTURE: props/rocks-foreground-cubic.png -> 0x1712638
CREATE OBJ: fern_foreground4
CREATE OBJ: rock_foreground_seaside1
CREATE OBJ: fern_foreground3
CREATE OBJ: rock_background_cubic2
CREATE OBJ: rock_foreground_cubic2
CREATE OBJ: rock_foreground_cubic1
CREATE OBJ: sfx_falloff_generator
CREATE OBJ: rock_foreground_seaside6
CREATE OBJ: rock_foreground_seaside7
CREATE OBJ: rock_foreground_seaside8
CREATE OBJ: rock_foreground_seaside5
CREATE OBJ: rock_foreground_seaside3
SET STARTING CYCLES: 192
mapping palette 14
get palette mapped: props/gate.png, 14 -> 0x1058aa0
mapping palette 3
get palette mapped: props/foliage-seaside.png, 3 -> 0xcb3650
mapping palette 3
get palette mapped: props/buildings/seaside-house-3.png, 3 -> 0x154df98
mapping palette 3
get palette mapped: props/seaside-house-door.png, 3 -> 0x13c5aa8
mapping palette 3
get palette mapped: props/buildings/seaside-house-parallax.png, 3 -> 0x1758720
mapping palette 3
get palette mapped: props/save_toilet.png, 3 -> 0x175a240
mapping palette 3
get palette mapped: props/plants-foreground.png, 3 -> 0x17601c8
mapping palette 3
get palette mapped: props/rocks-background-cubic.png, 3 -> 0x1766b40
mapping palette 3
get palette mapped: props/rocks-foreground-seaside.png, 3 -> 0x176c998
mapping palette 3
get palette mapped: props/rocks-foreground-cubic.png, 3 -> 0x17708e8
RUNNING GARBAGE COLLECTION FOR 120 OBJECTS...
PASS 1: 102 OBJECTS SAFE
PASS 2: 118 OBJECTS SAFE
RAN GARBAGE COLLECTION IN 1ms. Releasing 2/120 OBJECTS
PLAY: 0x1895838 ambient/house-interior-seaside.ogg -> -1
PLAY: 0x1895340 ambient/wind-blustery.ogg -> -1
PLAY: 0x1775c70 ambient/ocean.ogg -> -1
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
mapping palette 3
LOADTEXTURE: statusbar.png -> 0xcb4d20
CREATE OBJ: dust_cloud_run
CREATE OBJ: dust_cloud_jump
mapping palette 3
CREATE OBJ: dust_cloud_skid
in level constructor...
building...20335
done building...20335
LAYER -50 BUILT 0 tiles
LAYER -35 BUILT 0 tiles
LAYER -20 BUILT 0 tiles
LAYER -18 BUILT 0 tiles
LAYER -8 BUILT 4925 tiles
LOADTEXTURE: tiles/wooden-scaffold.png -> 0x12d9520
LAYER -7 BUILT 230 tiles
LAYER -6 BUILT 0 tiles
LAYER -5 BUILT 16200 tiles
LAYER -4 BUILT 0 tiles
LAYER -3 BUILT 0 tiles
LOADTEXTURE: tiles/wooden-bridges2.png -> 0x1479c00
LAYER -2 BUILT 698 tiles
LAYER -1 BUILT 0 tiles
LAYER 0 BUILT 0 tiles
LAYER 1 BUILT 0 tiles
LAYER 2 BUILT 0 tiles
LAYER 4 BUILT 0 tiles
LAYER 5 BUILT 0 tiles
LAYER 7 BUILT 0 tiles
LAYER 8 BUILT 0 tiles
LAYER 9 BUILT 0 tiles
LAYER 11 BUILT 0 tiles
LAYER 12 BUILT 0 tiles
LAYER 20 BUILT 0 tiles
LAYER 29 BUILT 0 tiles
LAYER 30 BUILT 980 tiles
LAYER 32 BUILT 0 tiles
LAYER 35 BUILT 0 tiles
LAYER 40 BUILT 0 tiles
LAYER 50 BUILT 0 tiles
LAYER 100 BUILT 0 tiles
done building tile_map...20940
done building hex_tile_map...21001
mapping palette 3
get palette mapped: tiles/wooden-scaffold.png, 3 -> 0x1a27b90
mapping palette 3
get palette mapped: tiles/wooden-bridges2.png, 3 -> 0x12d7748
done level constructor: 803
CREATE OBJ: water_controller
CREATE OBJ: seaside_house_1
LOADTEXTURE: props/buildings/seaside-house-1_solidity.png -> 0x195e188
LOADTEXTURE: props/buildings/seaside-house-1.png -> 0x1c33fc0
mapping palette 3
get palette mapped: props/buildings/seaside-house-1.png, 3 -> 0x1bef180
LOADTEXTURE: props/buildings/seaside-house-1_overlay.png -> 0x1c54870
mapping palette 3
get palette mapped: props/buildings/seaside-house-1_overlay.png, 3 -> 0x12c66e0
CREATE OBJ: world_1_cave_side_doorway_exterior
LOADTEXTURE: props/world-1-cave-entrance.png -> 0x1dd66c0
mapping palette 3
get palette mapped: props/world-1-cave-entrance.png, 3 -> 0x1dd68b0
CREATE OBJ: seaside_house_2
LOADTEXTURE: props/buildings/seaside-house-2_solidity.png -> 0x1c28d90
LOADTEXTURE: props/buildings/seaside-house-2.png -> 0x1dae358
mapping palette 3
get palette mapped: props/buildings/seaside-house-2.png, 3 -> 0x1ddc4a0
CREATE OBJ: seaside_house_cliff_1
LOADTEXTURE: props/buildings/seaside-house-cliff-1_solidity.png -> 0x1e4be48
LOADTEXTURE: props/buildings/seaside-house-cliff-1.png -> 0x1e4cba0
mapping palette 3
get palette mapped: props/buildings/seaside-house-cliff-1.png, 3 -> 0x1e4c798
CREATE OBJ: seaside_house_exterior_door
CREATE OBJ: seaside_house_2_upper_door
LOADTEXTURE: props/seaside-house-2-upper-door.png -> 0x1e0d450
mapping palette 3
get palette mapped: props/seaside-house-2-upper-door.png, 3 -> 0x1e0e1a0
CREATE OBJ: fish_green
LOADTEXTURE: enemies/fish-green.png -> 0x1e9dd68
CREATE OBJ: coin_silver
CREATE OBJ: rock_throwable_respawning
LOADTEXTURE: props/rock-projectiles.png -> 0x1e958d0
mapping palette 3
get palette mapped: props/rock-projectiles.png, 3 -> 0x202c088
CREATE OBJ: padlock
LOADTEXTURE: props/locks.png -> 0x20ce798
LOADTEXTURE: effects/particles3.png -> 0x20d09a0
CREATE OBJ: platform_swaying
LOADTEXTURE: props/rope-platform.png -> 0x20f5e40
mapping palette 3
get palette mapped: props/rope-platform.png, 3 -> 0x20f5460
LOADTEXTURE: wip/basket-mockup2.png -> 0x215f3d0
mapping palette 3
get palette mapped: wip/basket-mockup2.png, 3 -> 0x216b800
CREATE OBJ: platform_swaying_vertical
CREATE OBJ: piston_machine
LOADTEXTURE: props/piston-machine.png -> 0x219f148
mapping palette 14
get palette mapped: props/piston-machine.png, 14 -> 0x20f4598
CREATE OBJ: drive_line
SET STARTING CYCLES: 0
RUNNING GARBAGE COLLECTION FOR 219 OBJECTS...
PASS 1: 200 OBJECTS SAFE
PASS 2: 216 OBJECTS SAFE
RAN GARBAGE COLLECTION IN 3ms. Releasing 3/219 OBJECTS
CREATE OBJ: invisible_portal
CREATE OBJ: rope_angled_controller
LOADTEXTURE: props/rope-vertical.png -> 0x102dfe0
mapping palette 3
get palette mapped: props/rope-vertical.png, 3 -> 0xd0ceb8
LOADTEXTURE: props/rope-vertical-dark.png -> 0x10398b8
mapping palette 3
get palette mapped: props/rope-vertical-dark.png, 3 -> 0x12c5730
LOADTEXTURE: props/chainbit.png -> 0xd1fbc8
mapping palette 14
get palette mapped: props/chainbit.png, 14 -> 0x1493f00
LOADTEXTURE: props/elevator-track.png -> 0x14931d8
mapping palette 14
get palette mapped: props/elevator-track.png, 14 -> 0x1045d30
PLAY: 0x147f198 ambient/mech.ogg -> -1
PLAY: 0x20eae68 ambient/wind-blustery.ogg -> 0
PLAY: 0x20e85f0 ambient/ocean.ogg -> 1

**Comment by rkettering** [comment]
Due to the total rewrite we've made to our rendering engine, it's probable that this bug has been fixed, so I'm going to go ahead and close it.  Thanks for reporting it.
