### ISSUE TITLE
Ants spawned from anthills spawn oddly.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#122]
When an ant is spawned on top of an anthill, it appears instantly and stays in a static, frozen idle animation for about a second before it actually moves. The ant cannot be interacted with during this time, as far as I could test.

**Comment by rkettering** [comment]
This is the way they've always behaved - they're in a state called "attached objects" where they're displayed, visually, but they don't have any sort of interactivity with the rest of the objects in the game - they're totally "ethereal"/"pass-through".  Basically this is meant to symbolize them burrowing up out of the anthill, and then only becoming "part of the game" when they "pop" out the top.

Attached-objects are pretty limited in what they're capable of - I think we're unable to move them around, at all - the few cases where they've been used, they're always locked to "slightly above the parent's midpoint", and that's worked out well-enough for all of those cases that this has never had to be revised.  They were originally added to the engine way, way back in the beta days to handle the pilot of the robot vehicle (currently seen on dungeon-crawling as a boss fight), and during all the intervening time, we've never had a usage of this where we've needed some other position.

I think it would be nice to make these ants slowly ascend during their spawn animation, but it would be complicated enough, and the current behavior has been "good enough" for so long, that this is something I'm pegging to not be necessary for the next release.

**Comment by rkettering** [comment]
This has been improved a bit in 857897804c8c976ae7bb62ab11486a1837e49dc9 - at the very least, we now have the tools to do something better, because under the old `attached_objects` system we had no control whatsoever over placement or interactivity.
