### ISSUE TITLE
Dust cloud when landing not aligned properly.

### ISSUE THREAD

**Issue by ghost** [frogatto/frogatto#132]
When Frogatto lands falling straight down, he creates a dust cloud on either side.  If he's moving, however, the dust cloud is not centered correctly.

**Comment by marcavis** [comment]
From doing some testing, I believe it *is* centered correctly, but could perhaps be improved by imparting on them some of Frogatto's velocity_x.

**Comment by rkettering** [comment]
probably fixed a long time ago
