### ISSUE TITLE
Inaccurately-placed ambient sound source.

### ISSUE THREAD

**Issue by ActionJackalope** [frogatto/frogatto#134]
The ambient sound of squeaking from the metal platforms only plays when Frogatto stands on the left side of the platform.  The sound generator's range might need to be extended a little bit.

**Comment by DDR0** [comment]
Did ad58bb58936f3b29db831c87202ce087b367a4d9 fix it? Sound is broken here, so I don't really know - but it looks a lot more centered in the editor.

**Comment by rkettering** [comment]
ad58bb5 helped - it correctly centered it.  It still needed more distance to the falloff, which I've done in 21f4521
