### ISSUE TITLE
Dust cloud misaligned upon starting jump on an object

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#137]
When you jump, the dust cloud is up and to the left of where it should be… but only when you’re standing on an object.

**Comment by DDR0** [comment]
This has something to do with set(obj.parent, self.standing_on) in spawn_on_ref in frogatto_playable.cfg; although I don't know what. Commenting out the line fixes the bug, but then the objects spawned don't track the ground they were spawned on.

**Comment by marcavis** [comment]
I'm probably just papering over what is some confusing deeper issue, but fixed, for graphical purposes, by https://github.com/frogatto/frogatto/commit/9cfa1134577e477b90ce2feae901d37fc750bf56

**Comment by marcavis** [comment]
Fixed by https://github.com/anura-engine/anura/commit/f180b1ce97f57c6ff935d9a0dba52de7e7c8d72e and reversions of the tweaks I had made.
