### ISSUE TITLE
falling spike blocks in dungeon aren't part of hittable prototype (and thus can't damage anything)

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#145]
(no text)

**Comment by DDR0** [comment]
This is mostly fixed by 17120cc6523022e8eb47bdc053d3907370301321. However, the spiked block does not damage the player on its first descent only. It is possible that the winder.animation is not set to drop the first time, either.

**Comment by DDR0** [comment]
This issue has been reviewed by @rkettering and ought to be closed by a925e7813535345a02f8f201af94653b926a1d99.
