### ISSUE TITLE
Unclear asset licensing

### ISSUE THREAD

**Issue by kozross** [frogatto/frogatto#148]
The following directories are exempt from this, and all of their contents are copyrighted to the frogatto team.
    - data/levels, which contains all of our level files
    - images/characters, which contains all of our main-character art
    - images/tiles, which contains our tile art
    - sounds, which contains our sound effects
    - music, which contains our background music

Am I to understand that the listed assets are 'all rights reserved'? You specify they are not CC-BY-3.0, but specifying that they are 'copyrighted to the frogatto team' tells me absolutely nothing, as licensing and copyright transferral are different things.

**Comment by marcavis** [comment]
Yes, those files are covered by the default, "all rights reserved", copyright.
