### ISSUE TITLE
Black screen when leaving Frogatto's home

### ISSUE THREAD

**Issue by KroArtem** [frogatto/frogatto#158]
Ubuntu x86_64, using Anura + Frogatto from git repos.
(Frogatto -- 4de4a759210e9383a278f209a117ede8c2cc3aff, Anura -- 3c263999724ad8ebde44d35cff591efc486f8695)

When you leave Frogatto's home for the first time, it should, as @rkettering  said, show the sky and then come back to the house, but instead, it shows black screen, then goes up to the surface and only then comes to Frogatto's house.

![2015-08-27 23 17 47](https://cloud.githubusercontent.com/assets/1813101/9546347/99c38e2c-4d9a-11e5-8798-389cd335c715.png)
![2015-08-27 23 17 55](https://cloud.githubusercontent.com/assets/1813101/9546348/99c4154a-4d9a-11e5-8309-5d8ed132f138.png)

**Comment by rkettering** [comment]
Fixed, now - it was a change to the magnitude of the "set screen position" command
