### ISSUE TITLE
Text of video options is messed

### ISSUE THREAD

**Issue by KroArtem** [frogatto/frogatto#159]
Ubuntu x86_64, using Anura + Frogatto from git repos.
(Frogatto -- 4de4a75, Anura -- 3c263999724ad8ebde44d35cff591efc486f8695)

When you launch Frogatto with standart resolution (I suppose it is 800x600), there is a problem with video options, see screenshot for more info:

![2015-08-28 16 46 20](https://cloud.githubusercontent.com/assets/1813101/9548199/cf06a3b4-4da7-11e5-933e-cc6f1c626565.png)

**Comment by rkettering** [comment]
This issue was moved to anura-engine/anura#122
