### ISSUE TITLE
implement a better visual effect (ideally similar to the "autocast active" effect seen in warcraft/dota), to indicate that a super-shot is active

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#172]
Essentially the effect in question is like a marching-ants filter, except with really wide cycles - so wide that  a full rotation around the topographical edge leaves us with two white segments, and two dark.  Furthermore, the white segments are often set up to linearly "fade out" into the black as a gradient.

**Comment by DDR0** [comment]
There is an glitch where there is a one-pixel offset along the window's diagonal line.

**Comment by rkettering** [comment]
This is done and it looks really nice. :smile:
