### ISSUE TITLE
The new dungeon wall decorations need some slight graphical improvements (a few edges that don't blend in, here and there).

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#174]

**Comment by Phanterm** [comment]
Could you post a screenshot highlighting some of these areas, just for reference?

**Comment by rkettering** [comment]
https://github.com/frogatto/frogatto/commits/master/images/props/dungeon-stonework.png  this is the file in question.  That link points to the commit history, showing all the different "tune ups" I've done.  Several of those props are totally finished.

2 objects on the sheet that need more rendering are:
- the top row, second-from-the-left (what looks like a single 'capital' arch that could be attached to a pillar).
- bottom row, right-most object (which looks like a distant, open doorway)

**Comment by rkettering** [comment]
I've done few final tweaks to this - thanks to all the help you've done, we can consider this done for the next release.
