### ISSUE TITLE
Blind alley is completely impossible with the current lighting mechanics.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#182]
abilities don't give enough "lit time".

**Comment by Phanterm** [comment]
I'm unfamiliar with the new lighting system. Is this something that needs to be fixed, or is it that our torches are simply out of date?

**Comment by rkettering** [comment]
The way that our "circle light" function removes the darkness seems to have some sort of built-in delay, and short spurts of it don't provide nearly as much light as they did before.  Amongst other things it seems like the engine code was enhanced to provide some sort of gradual increase in lighting amount as the command is fired, rather than just immediately being at full brightness.  This is cosmetically nice, but causes a real loss of control for us on the client side - it may really screw with attempts to make rapidly flickering lights.

Furthermore, at the same settings as before, lighting on partially (rather than completely) dark levels now seems moderately darker.

So - specifically concerning Blind Alley:
Previously, cherry-tapping the fire ability would immediately provide a wide, strong circle of light - giving you enough time to see your surroundings at the cost of maybe only 1/6 of your mana pool.  Now, one has to pretty much exhaust their entire mana pool just to push the "lighting amount" up to being enough to see anything.

**Comment by rkettering** [comment]
Should be fixed with the new lighting system.
