### ISSUE TITLE
Need to decide on a dole-out point for the energy-shot

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#196]
the energy shot is strictly necessary to pass certain alteborea levels

**Comment by Phanterm** [comment]
I was thinking about it the other day, and somewhere in Tempo or the forest before the path branches seem to be an ideal way to proceed. Alternatively, we could block certain parts of both the alteborea and swamp to force the player back to the dole-out area to complete that objective. 

We could have a quest for it, even. Maybe the mayor of Tempo has some sick villagers (likely from the mutation and corruption in the swamp) and Frogatto is asked to retrieve ingredients in either area up to the point where they can no longer proceed without the energy shot (and the rationale can be that the NPC used some magic jumbo to create a protective barrier, and the energy shot is the spell to break them.

**Comment by Phanterm** [comment]
Alternatively, we could have a terminally ill NPC pass it down to the player after completion of the aforementioned quest. Kinda like King from Cave Story. (I would use the edit function for my previous post, but I am on my phone)

**Comment by Phanterm** [comment]
I think we can close this now that it's more or less decided that Prospera will dole out the energy shot.
