### ISSUE TITLE
Cannot place a Frogatto_playable in the editor without crashing.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#234]
This also means that I cannot restart levels in anura without getting an assert.

**Comment by DDR0** [comment]
I can't reproduce this now, so I'm going to assume it's been fixed. Please re-open it if it's not, @Phanterm.

**Comment by Phanterm** [comment]
I wasn't able to reproduce it either. I think it was tied to a level, and
subsequently fixed in an unrelated update.

On Mon, Jan 18, 2016 at 11:04 AM, David Roberts <notifications@github.com>
wrote:

> I can't reproduce this now, so I'm going to assume it's been fixed. Please
> re-open it if it's not, @Phanterm <https://github.com/Phanterm>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frogatto/frogatto/issues/234#issuecomment-172592093>.
>



-- 
Hunter Kennoy
Workforce Training & Development Student Manager, Berea College
101 Chestnut St.
Berea, KY 40404
502-352-0133
