### ISSUE TITLE
Need a buzz-saw loop sfx for the ones in the dungeon

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#240]
can oscillate in loudness because the buzz-saws flip the direction they spin towards, every few seconds (aka they speed up and slow down, every few seconds)

**Comment by DDR0** [comment]
I believe this is closed by https://github.com/frogatto/frogatto/commit/b689f3ebd71a3b6f03d20c5bb41a0c7570cef444, "New sound for saws in dungeon area".
