### ISSUE TITLE
Assert when loading game on grassy-path.cfg.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#269]
![image](https://cloud.githubusercontent.com/assets/3878045/12990997/d88005b2-d0d2-11e5-9e14-2e1caf9bd1ff.png)

**Comment by DDR0** [comment]
I can't reproduce this. It might be that your Anura is out of date, or that the issue has simply been fixed in the past 10 hours.

**Comment by rkettering** [comment]
Talked to him - this came from **loading a saved game**, not just loading that level.

**Comment by DDR0** [comment]
Reproduced.

**Comment by DDR0** [comment]
The fix for this will probably be to make on_load fire before the check for the animation frame being valid is performed.
