### ISSUE TITLE
Light sources do not provide adequate lighting.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#271]
![image](https://cloud.githubusercontent.com/assets/3878045/13127345/79f1f548-d594-11e5-8dee-2fe61239ea2f.png)

From blind-alley.cfg

**Comment by DDR0** [comment]
Reproduces on blind-alley.cfg but not on nenes-basement.cfg. 

(Blind alley would seem to be just what it says on the tin, no?)

**Comment by rkettering** [comment]
https://github.com/frogatto/frogatto/issues/182  this is closely related, and we'll want to close both of these at the same time, when we fix this: https://github.com/frogatto/frogatto/issues/182

**Comment by rkettering** [comment]
Fixed now.
