### ISSUE TITLE
Assert when loading the hanging-platforms.cfg level.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#272]
![image](https://cloud.githubusercontent.com/assets/3878045/13156728/9087ad56-d649-11e5-83d3-365ec30751a0.png)

Having a hard time reproducing, as it seems to happen inconsistently.

**Comment by rkettering** [comment]
Framebuffers are created by the distortion effect used by water...  that's my only lead on this right now.

**Comment by rkettering** [comment]
Flagging as hopefully fixed for now;  if we get further crash reports, we'll pass them to the windows maintainer.
