### ISSUE TITLE
frogatto.com low on disk space

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#273]
Before 1.4 is released, we should look at upgrading the frogatto.com server with a slightly larger disk. (It is fine for now, though.)

> 18<26crimson_penguin18> Rotonen: I deleted a few files btw, about 900MB; might buy a bit of time, but we still need to deal with it
> 18<24Rotonen18> with so many not-from-distro things going on at the same time it's indeed getting a bit crowded
> 18<24Rotonen18> you have 30G storage, swap takes 4G, your forum takes 5G, your other web things take 5G, the hhvm build temp takes 2G, database backups take 1G, the rest is unavoidable systems usage
> 18<24Rotonen18> you're not currently very disk-bound in your basic loads, so you're also fine with the filesystem performance hit
> 18<24Rotonen18> but the solution is to upgrade the server by one notch once you expect traffic to start coming your way

**Comment by rkettering** [comment]
`<Rotonen>	Jetrel_bot: there are no disk space concerns at this point`
