### ISSUE TITLE
Remove all instances of transform()

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#278]
Transform doesn't have type inference, and it's a decent candidate for removal anyways.

Transform was " a more limited and faster version of map()", and operated similarly, though one might often find that `v` was used in place of `value`, and `i` in place of `index`

**Comment by DDR0** [comment]
There are 4 occurrences of the function in our code, according to grep.

**Comment by rkettering** [comment]
Now we need to remove the actual function.

**Comment by DDR0** [comment]
Closed by 59396c32a7f0 in Anura.
