### ISSUE TITLE
Thrown ants survive collision against upside down enemies

### ISSUE THREAD

**Issue by marcavis** [frogatto/frogatto#298]
When thrown at enemies that are upside down, they always survive; the latter either is hurt by the impact, or is bypassed entirely, thus both survive.
Test case at https://github.com/frogatto/frogatto/commit/654e5540abfc0e0366461ccbc198c98ea06b97b3

**Comment by rkettering** [comment]
Fixed in: f0caba3a9a1e292b519e924e806625cfe10ef769 90b6e7c3c62261ed2e621fc93bc445388a850fee
