### ISSUE TITLE
noticeable slowdown on old hardware - seems to happen due to the floor-locating functions

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#303]
Was doing some unrelated testing on celadon-clearing, and whilst most stuff is fast enough, when I turned on the `supes` cheat and started flying, the game would go noticeably slower when floating over the large early-level chasm, then when over a very close platform; leading me to suspect the function (likely to place the player's shadow) is having to reach too far down and process too much.

There's likely some opportunity for optimization in not searching past the screen bounds, since the shadow's purely cosmetic - and just removing (visually?) the shadow temporarily during that chunk of time.

**Comment by davewx7** [comment]
Did you try pressing f7 to bring up the profiler and get a performance
profile of what's going on?

**Comment by rkettering** [comment]
We've solved the floor-finding slowdown by optimizing the function it calls in anura.   We've still got a slowdown on two other things - one being the `is` type operator, and the other being calling nested functions, but those can be filed as other issues.
