### ISSUE TITLE
only allow a single running instance of the game

### ISSUE THREAD

**Issue by acsipak** [frogatto/frogatto#309]
Only allow a single running instance (per user?) of the game.

(My child occasionally clicks too many times on the desktop icon, which results in a second instance firing up, which results in some performance loss. Also the game music is weird.)

If there's a valid use case for running multiple instances, then it should be an opt-in feature which can be enabled via command line switches.

**Comment by rkettering** [comment]
Thanks for filing this issue, but I think we're going to pass.  Any further issues like this ought to be filed over on anura's tracker instead:  https://github.com/anura-engine/anura/issues

**Comment by acsipak** [comment]
I opened an issue on anura'a tracker, as suggested, see: https://github.com/anura-engine/anura/issues/166
