### ISSUE TITLE
Black Box Texture

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#329]
Running Git 9b98879 (2017-07-21) as `./anura --level=to-nenes-house.cfg`, I get a strange black box where one of the trees is.

It pulses a red tree if I mouse over it in the editor.

![image](https://user-images.githubusercontent.com/862627/28453474-6d8bc3d6-6dac-11e7-926e-c940a4c760e1.png)

**Comment by davewx7** [comment]
Fixed
