### ISSUE TITLE
There's a half-pixel of black under the tongue item in the inventory screen.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#330]
- Run the game with `./anura --level=to-nenes-house.cfg --hax`.
- Hit e for inventory screen.
- Observe the tongue detector, which has a line underneath it. It shouldn't.

https://cdn.discordapp.com/attachments/271875323417591818/337855244044075008/Spectacle.B32588.png

**Comment by al0fdf** [comment]
No longer present:
![image](https://user-images.githubusercontent.com/104121665/195495316-7ff3877f-5b2c-4689-bf36-7b01272bedf0.png)
