### ISSUE TITLE
Swimming animation stops after the cycle is finished if both up and down arrow keys are held.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#331]
Frogatto's swimming animation stops after the cycle is finished if both up and down arrow keys are held. This does not happen if both left and right arrow keys are held.

**Comment by rkettering** [comment]
Fixed in:  709dec497 2b9a8efc81b5771618428701f47bc22d16dddaa4 7eb216b034cf8e5a27617a02e4655e6cee36e627
