### ISSUE TITLE
Water background not being displayed properly.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#332]
![image](https://user-images.githubusercontent.com/3878045/28998653-9d190b46-79e5-11e7-9b42-07f9da84d137.png)

There is an issue with parts of the water background showing up with darkened stripes. Additionally, parts of the water are black unless the player swims down far enough.

Tested on rain-test.cfg

**Comment by rkettering** [comment]
(What I believe to be) The real issue:
Our palette-shifting code does not respect alpha-channels.  I think they get turned full-opaque.

**Comment by DDR0** [comment]
This seems to work now. :slightly_smiling_face:
I've pulled out the texture issue into bug #419.
