### ISSUE TITLE
Returning to Title Screen continues to play any ambient SFX currently playing

### ISSUE THREAD

**Issue by LevieDAudio** [frogatto/frogatto#333]
While an looping ambient sound effect is playing in the world (such as a waterfall), exiting out to the Title Screen from the menu will warp the player back to the title screen, but the ambient sound effects will continue playing on a loop.

**Comment by rkettering** [comment]
Notably this only happens when you click the 'return-to-titlescreen' button.

**Comment by rkettering** [comment]
Seems to be fixed, now.
