### ISSUE TITLE
some users can't use Q and W to toggle abilities

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#337]

**Comment by boamaod** [comment]
I may have this issue with current Frogatto on Ubuntu 16.04.6 compiled from Anura source code.

I can switch abilities all right, but when I receive Fire Talisman from Nene there are just 5 slots of this in ability switcher and no tongue any more. However in water I can switch between bubbles and fire, but there is also too many of pairs of them displayed in ability switcher.

If you have any idea how to fix this or get past it, please let me know, I might give it a try.

**Comment by DDR0** [comment]
Hi Boamaod, indeed, it seems when I have abilities I can't select tongue again. Thanks for reporting this! I'll look into a fix, hopefully something simple broke.

**Comment by DDR0** [comment]
Ah. We seem to be wiping inventory whenever we add something to it, at the moment. Strange.

**Comment by DDR0** [comment]
I'll be able to have a look at this tomorrow after work, hopefully. We should be able to fix your current game, too.

**Comment by DDR0** [comment]
@boamaod, this should be fixed for future runs now by commit 082eb8a44. To fix your current run, hit ctrl-d to bring up the in-game debug console, then enter `initialize_items` and press enter. If you have any questions or comments, please drop by our development [Discord](http://discord.gg/Uws7GYw). :)

I'm going to leave this issue open, as we don't seem to have diagnosed the original underlying cause yet.

**Comment by rkettering** [comment]
Probably fixed at this point.
