### ISSUE TITLE
Colliding with a fan causes an Assert 

### ISSUE THREAD

**Issue by LevieDAudio** [frogatto/frogatto#339]
![frog bug 170817 fan collision a](https://user-images.githubusercontent.com/30911932/29483533-67849052-84a0-11e7-8061-f32c58f0c3ca.png)
![frog bug 170817 fan collision b](https://user-images.githubusercontent.com/30911932/29483534-68bdc86c-84a0-11e7-92ad-8a0e2926be04.png)

**Comment by rkettering** [comment]
Fixed.
