### ISSUE TITLE
Loading a save file saved at Fan House causes an Assert

### ISSUE THREAD

**Issue by LevieDAudio** [frogatto/frogatto#340]
![frog bug 170817 fan house reload a](https://user-images.githubusercontent.com/30911932/29483546-a6cdb0c2-84a0-11e7-93d1-e15181551574.png)
![frog bug 170817 fan house reload b](https://user-images.githubusercontent.com/30911932/29483548-a7abf436-84a0-11e7-9b3d-243aae10d1ff.png)

**Comment by Vultraz** [comment]
This was fixed.
