### ISSUE TITLE
Save Points don't trigger when colliding with them upon entering a level

### ISSUE THREAD

**Issue by LevieDAudio** [frogatto/frogatto#341]
Upon moving to a different level, Frogatto's collision with a Save Point doesn't trigger a game-save if he spawns too close to it.

The Player has to run far away from the Save Point, then back, and then touch it again in order to save their game.

![frog bug 170817 save point doesnt work when entering from left](https://user-images.githubusercontent.com/30911932/29483572-04d14f08-84a1-11e7-9d59-af7cee29d6f6.png)
Example: Frogatto spawns roughly here when entering this level, but the game doesn't save.

**Comment by Phanterm** [comment]
Good catch. Moving the save point further out will fix this.

Further, perhaps we can make the case for adding a visually represented cooloff period for save points. That way it becomes clear when players are able to go near the save point again in order to use it.

**Comment by Phanterm** [comment]
Closing this, as we will now eliminate this issue as we encounter it by moving save points outside of the entrance/exit areas for levels. :)
