### ISSUE TITLE
On rare occasions, frogatto's swallowed object can get 0hp, and will disappear when spawned

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#345]

**Comment by DDR0** [comment]
This is probably a duplicate of https://github.com/frogatto/frogatto/issues/457, or at least related to it.

**Comment by DDR0** [comment]
[save(1).cfg.txt](https://github.com/frogatto/frogatto/files/9035389/save.1.cfg.txt)

**Comment by rkettering** [comment]
Fixed in e13ae8317
