### ISSUE TITLE
Ferns do not wave in the wind as they used to.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#347]
Ferns, such as `fern_foreground1`, used to distort as they waved in the wind. However, during the transition to vertex shaders from `custom_draw`, this behaviour was lost.

The ferns still do bob around, but they remain undistorted as they do so.

To reproduce, run `./anura --level=to-nenes-house.cfg`

------

![spectacle m29559](https://user-images.githubusercontent.com/862627/32361175-8e2daada-c01a-11e7-8079-2c32ff8f09ab.png)

**Comment by Phanterm** [comment]
For clarity's sake, the ferns still _move_, but they don't really blow in the wind so much as they quiver in terror.

**Comment by DDR0** [comment]
iirc, we removed something called… `custom_draw`, maybe? Basically, it allowed us to specify a box and points around that box to distort the graphic drawn. However, it was removed for reasons which I don't know and we haven't made a shader to do the same thing yet because none of us know how to.

**Comment by rkettering** [comment]
Fixed it by reverting to the old code, since we don't have a way of injecting additional vertices into the vertex shader.
