### ISSUE TITLE
Add additional emotes and animations for the generic Kitty.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#351]
-Sitting Kitty A (Happy face, legs swinging!)
-Sitting Kitty B (Normal face, legs swinging)
-Sitting Kitty C (Normal face, no legs swinging, slight bobbing, etc)

or honestly, we can do anything that works with the dialogue with animations like this ^

-”Eating” Kitty
-Chef Kitty **(where is the lamb _sauce_)**
-Kitty idle animations/emotes. Should reflect dialogue of a given kitty npc. I‘ll take a crack at it. [/pugna] 
-Helper Kitty (janitorial kitty or kitty kneeling down and getting their hands dirty)
-Kitty chilling out. Headphones and half-circle eyes.

**Comment by rkettering** [comment]
Finished.
