### ISSUE TITLE
Develop a system that retains player momentum when traversing levels through vertical portals.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#354]
Mechanic should retain player momentum / add momentum upon ascending to a new level via jumping or other. The problem right now is that when Frogatto goes “up” to a new level, they simply appear on a solid surface. Not sure how tricky this would be, but one solution could be for the game to globally remember the player’s velocity upon ascending or descending, and apply it upon transition. 

Especially when jumping up to a new level. It always pulls you out of the experience to expect to transition in mid-air and instead appear on the ground immediately.

**Comment by rkettering** [comment]
I really don't care about this, personally.  What we've got feels fine to me.
