### ISSUE TITLE
The remainder of Frogatto's sprites need to be converted to the new style.

### ISSUE THREAD

**Issue by Phanterm** [frogatto/frogatto#358]
Certain animations such as the jump during fat-mode still retain the hard outline existing before the style change. It's very apparent and should be updated.

Todo:

- [x] taking damage sprites in `frogatto-spritesheet2.png`
- [x] turning sprites in `fat-frogatto-spritesheet1.png`
- [x] talk, nod, and raisedfinger sprites in `fat-frogatto-spritesheet3.png`
- [x] angry in `fat-frogatto-spritesheet4.png` (also needs a fat version)
- [x] the falling/faceplant animation doesn't have a fat version

everything in `frogatto-spritesheet-idle.png`.   We don't need fat versions of these, since we're using code to not display these if the player is fat, but we do need to fix the edging.
- [x] first "eyepull" idle animation
- [x] second "croak" idle animation
- [x] third "shrug\what gives?" idle animation
- [x] we very likely aren't even using that third idle animation.  We should.

**Comment by rkettering** [comment]
Todo:

- [ ] taking damage sprites in `frogatto-spritesheet2.png`
- [ ] everything in `frogatto-spritesheet-idle.png`
- [ ] turning sprites in `fat-frogatto-spritesheet1.png`
- [ ] talk, nod, and raisedfinger sprites in `fat-frogatto-spritesheet3.png`
- [ ] angry in `fat-frogatto-spritesheet4.png`

Note also:
- [ ] we very likely aren't even using that third idle animation.  We should.
- [ ] that fat angry animation isn't actually fat.
