### ISSUE TITLE
A few objects need to be exempt from the usual shader chain because they use palettes.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#361]
- [ ] stalactites
- [ ] milgram's missile-shooters (maybe strip palette usage here?)
- [ ] falling bricks

**Comment by Vultraz** [comment]
Also the diamond projectile thingies in the forest levels that come in batches from the center of those stone pillars.

**Comment by rkettering** [comment]
Was fixed by dave by folding the palette logic for the default shader into the custom, modder-defined shader.
