### ISSUE TITLE
Release a 64-bit Mac version of Frogatto

### ISSUE THREAD

**Issue by Thunderforge** [frogatto/frogatto#364]
When running Frogatto 1.3.2 (my copy is from the Mac App Store) on macOS 10.13.4, the following warning appears:

<img width="532" alt="frogatto 32-bit" src="https://user-images.githubusercontent.com/6200170/38772324-4ed744cc-3ff9-11e8-9009-a20cd86fc219.png">

Clicking on the "Learn more…" button leads to [this Apple support page](https://support.apple.com/en-us/HT208436) explaining that 32-bit apps will not be supported in future versions of macOS, and that developers will need to update the app to be 64-bit compatible.

Ideally, an Anura 4 version of Frogatto would be released as a 64-bit Mac app, but given that the writing is on the wall for 32-bit apps on macOS, it may be safer to update the 1.3.x codebase with a 64-bit compatible version. @galegosimpatico has reported their initial attempts to do that on [this Anura issue](https://github.com/anura-engine/anura/issues/218).

Whichever route is decided, a 64-bit Mac version of Frogatto will be required for the long-term viability of Frogatto on macOS.

**Comment by rkettering** [comment]
This is finished internally, and will happen as part of the next release.

**Comment by galegosimpatico** [comment]
This is loosely related to https://github.com/anura-engine/anura/issues/261. Facilitating the transition from 1.3 to _1.4_ would increase the chances of stepping in the case.
