### ISSUE TITLE
Need to prioritize ambient sounds so they are guaranteed not to get bumped.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#370]
Sometimes our ambient sounds don't play; probably because we've flooded the available sound channels and don't have any left.   We need to mark them with some sort of priority so they're guaranteed to always play.

**Comment by DDR0** [comment]
Jetrel - Today at 23:36
@DDR   well, it's weird, because Dave says we shouldn't have any such problem with the new API
But multiple testers have reported situations where the ambient sounds just go silent

**Comment by rkettering** [comment]
Haven't seen this in forever, just going to blithely marked it as fixed and pray.
