### ISSUE TITLE
Investigate perf issues on plagued-mine

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#373]
Something's slowing the FPS down, there.

**Comment by DDR0** [comment]
I've had a shot at debugging this, playing through the level normally. I can't trigger the slowdown on my relatively beefy machine.

**Comment by Vultraz** [comment]
Seems better now after Dave's removal of the gray worm solidity calculation recursion.

**Comment by DDR0** [comment]
@rkettering, can I close this or do you still want to have a look at it?

**Comment by DDR0** [comment]
I'm closing this as it has probably been fixed by now.
