### ISSUE TITLE
Gameplay issues arising if defeating Gazer boss before talking to Prospera

### ISSUE THREAD

**Issue by Vultraz** [frogatto/frogatto#374]
During my playthrough, I found and defeated the Gazer boss before meeting and talking to Prospera. This is currently buggy and results in a large number of breakage.

- [x] 1. Opening dialog for the boss fight needs a variation in case you haven't met Prospera.
- [x] 2. Being teleported to the Promontory after the boss fight doesn't correctly set some flag, and the game thinks this is your first meeting as if entering from Pinecone Park.
- [x] 3. If you enter the house without triggering the "_hello who are you_" dialog, you don't get the appropriate "_hello, wow, you already defeated the boss before I even asked you!_" dialog (see [this forum post](https://forum.frogatto.com/t/prospera-gets-a-surprise/479) for a draft of the latter by ActionJack).
- [x] 4. If you head right first and trigger the "_hello who are you_" dialog, you get transported inside the house and the characters are positioned incorrectly, backs to each other.
- [x] 5. If you do 3, once you have the energy talisman and head back outside, Prospera is still standing there! Very likely she doesn't despawn there until the initial "hello who are you" dialog is done.
- [x] 6. It is also still possible to trigger that introductory dialog by heading right, even after acquiring the energy talisman. If this happens, you're teleported back inside the house, but nothing happens, you can't move, no dialog plays, and what have you. You're stuck.
- [x] 7. If you return to the Promontory later (such as if you want to give her statues), you can't reach her house since the lift in that level isn't running.

**Comment by rkettering** [comment]
I think we've correctly fixed all of this, now.
