### ISSUE TITLE
Font-generation rakefile doesn't seem to work.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#391]
In utils/font-generation, there is a rakefile which should generate all the non-latin-family font glyphs we need. It doesn't seem to work, claiming it `Don't know how to build task '../../po/zh_CN.po' (see --tasks)`.

**Comment by DDR0** [comment]
I've updated the rakefile to generate a new font in 92acdd1c5e90f59ce8b37ec39a9556a22593e87e, but I haven't tested it as it can't run to completion. :confused:

**Comment by hagabaka** [comment]
Does `zh_CN.po` exist anywhere? It's the file that contains the Simplified Chinese translation. If I remember correctly, you can get these files from Transifiex. @marcavis

**Comment by hagabaka** [comment]
I've updated the scripts to use the correct paths to find files, so they should work now.

**Comment by hagabaka** [comment]
I actually undid that change, because I thought there was no problem with space any more. But I was wrong. 568e95c does fix this for me.

**Comment by DDR0** [comment]
Excellent, everything seems to work now. Thanks, Hagabaka. :grin:
