### ISSUE TITLE
In-game menu appears to be unusable.

### ISSUE THREAD

**Issue by pbogdan** [frogatto/frogatto#397]
Selecting any option from the in-game menu (brought up via the ESC key) causes the game to exit immediately.

**Comment by galegosimpatico** [comment]
Close as "norepro"...

**Comment by galegosimpatico** [comment]
Parts of this are "wontfix" because correspond to code that's going to be discarded because wholly replaced.

**Comment by DDR0** [comment]
Very curious, indeed, but I can't reproduce it either.
