### ISSUE TITLE
Are images/effects under CC0 or CC-BY-3.0?

### ISSUE THREAD

**Issue by dvhx** [frogatto/frogatto#400]
Hi.

In license file only few directories are "all rights reserved", the rest is CC-BY-3.0. I'm asking just to be sure, does it mean that images/effects/ are under CC-BY-3.0?

**Comment by rkettering** [comment]
Yep - they’re intended to be usable by other projects, since they’re generic and aren’t related to our characters/story.

All we’d ask is to give us credit and keep us in the loop if you do something cool.

Thanks, and good luck!
