### ISSUE TITLE
new lights break saving

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#409]
```
2126 ▸·······▸·······▸·······▸·······▸·······"light_circular": q(ILLEGAL TYPE TO SERIALIZE: (loading 2014ec77012b422790dda40a1d9408cb)),
```
log at https://cdn.discordapp.com/attachments/225816341737766912/693563384104222811/message.txt

originally reported by juli#0046 on 2020-03-28

notes: Maybe caused by `light_controller.cfg:light_circular`. Potential fix may be to just regenerate the light on load and not save it at all.

**Comment by cpdef** [comment]
hi btw. i'am "juli" on discord. It did seem to happen after i'am walking to those save-points sometimes.
To repair the file i removed the object containing the
`"light_circular": q(ILLEGAL TYPE TO SERIALIZE: (loading 2014ec77012b422790dda40a1d9408cb)),`
from the file. It was just a shot in the blue but it worked out

**Comment by DDR0** [comment]
Update: Now you can generally load the levels but they're dark.

Symptoms:
  - Fires in hearths go out.
  - Lights disappear.

**Comment by rkettering** [comment]
This got fixed when we did all the updates to make attaches serialize correctly.
