### ISSUE TITLE
vm overflow maggot_white_controler

### ISSUE THREAD

**Issue by cpdef** [frogatto/frogatto#410]
Hi i'am at moment doing a playthrough in the dev version. It has sometimes some bugs, luckily i can resolve them by commenting buggy parts out or something in the ffl files.
This time i maybe found also a solution for it. I don't realy know FFL but i learn it a bit by reading the files. So here is the actual bug:
`ERROR: custom_object_functions.cpp:3405 : NOT AN OBJECT!
CRITICAL: formula_vm.cpp:72 ASSERTION FAILED: Overflow in VM: in Virtual Machine: At modules/frogatto/data/objects/enemies/bugs/maggot_white_controller.cfg 21:
def(int u, int v, int counter) -> [int,int] if(solid(level,u-1,v,2,2), if(c...
^

---VM:
-->0: OP_CONSTANT 0 ( "@eval def(u,v,counter) if(solid(level,u-1,v,2,2), if(counter<max_counter, _find... )
   2: OP_LAMBDA_WITH_CLOSURE

---STACK---

CRITICAL: At modules/frogatto/data/objects/enemies/bugs/maggot_white_controller.cfg 21:
def(int u, int v, int counter) -> [int,int] if(solid(level,u-1,v,2,2), if(c...
^

At modules/frogatto/data/objects/enemies/bugs/maggot_white_controller.cfg 21:
if(solid(level,u-1,v,2,2), if(counter<max_counter, _find_ceiling_open(u,v+2...
^

At modules/frogatto/data/objects/enemies/bugs/maggot_white_controller.cfg 20:
if(solid(level,u-1,v,2,2), _find_ceiling_open(u,v,0), _find_ceiling_solid(u...
^

At modules/frogatto/data/objects/enemies/bugs/maggot_white_controller.cfg 37:
[add(_spawn_countup, 5), if(_spawn_countup >= spawn_frequency and number_ne...
^
`

You can find it in the sourcecode here:
https://github.com/frogatto/frogatto/blob/master/data/objects/enemies/bugs/maggot_white_controller.cfg#L19#L22

in the formular.cpp of anura the max_ffl_recursion is set to 100, so i bet the solution is either
setting the max_ffl_recursion there to 2000+x or setting the max_countin the given file to 100-x.
With x i mean there has to be a bit buffer, because the function is already invoked by other functions.
My solution was setting max_counter to 90.

**Comment by rkettering** [comment]
I've recently run into the same issue and did a fix - thanks for bringing this to our attention!  The diagnosis you had was exactly what's wrong.
