### ISSUE TITLE
Coin can be clipped with large windows on main screen.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#412]
![image](https://user-images.githubusercontent.com/862627/82875655-82136100-9eec-11ea-87cd-a164fab9450a.png)

Note: The UI _isn't_ clipped by the level boundaries on the left side of the screen, just the coin on the right.

**Comment by rkettering** [comment]
We've done a couple of tests, and this seems to be confirmed as fixed.
It was being caused by being out-of-level bounds.
