### ISSUE TITLE
Gamepad (Controller) can control menu but not Frogatto.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#413]
Controllers: xbox, whatever weird thing from Logitech I have
OS: Windows, Linux
Build: Git on 2020-10-22

Issue: Controllers seem to be usable to control the escape menu of Frogatto, but can't actually make Frogatto himself move.

**Comment by al0fdf** [comment]
Partially fixed in https://github.com/anura-engine/anura/pull/334
