### ISSUE TITLE
Backgrounds sometimes don't draw soon enough when going down.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#419]
On `rain-test.cfg`, the water background doesn't draw until you swim quite some way down. Note the black region near the bottom of the picture below.

It feels like it forgets to compensate for the difference between screen pixels and level pixels, perhaps?

![image](https://user-images.githubusercontent.com/3878045/28998653-9d190b46-79e5-11e7-9b42-07f9da84d137.png)

This issue was originally reported by Phanterm as a note in issue #332.

**Comment by rkettering** [comment]
Gonna close this one;  we can reopen it if we have ongoing issues with it.
