### ISSUE TITLE
Saving then loading twice duplicates throwable respawing box.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#420]
Saving and loading and loading again duplicates the throwable box on `--level=dark-corridor.cfg`.

Save, then load.

![image](https://user-images.githubusercontent.com/862627/99188380-80468f80-2710-11eb-9a6a-f94b43f1e21b.png)

And load again.

![image](https://user-images.githubusercontent.com/862627/99200748-063bf800-275c-11eb-89f1-27b5f3998cba.png)

There are now two crates.

**Comment by DDR0** [comment]
![image](https://user-images.githubusercontent.com/862627/163087671-dc995dfb-18ef-45ea-bc00-158aa74ae31b.png)

**Comment by al0fdf** [comment]
Fixed in https://github.com/frogatto/frogatto/commit/7c0745208e248ea25bb7e0b18b6a12403ca1763a
