### ISSUE TITLE
Water beetles crash the game when tongued.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#422]
![image](https://user-images.githubusercontent.com/862627/103070423-40c45c00-4576-11eb-97e9-4f5276d2563c.png)

**Comment by galegosimpatico** [comment]
Please name a level where this can be easily reproduced.

**Comment by DDR0** [comment]
There is a reproduction on `--level=splash-hop.cfg`.

Additional notes: The water beetle must be in the water for this to occur.

(Also, definitely ping me on Discord if you need a response to something like this in a timely manner, GH is a bit quiet about notifying me. I expect I blackholed its emails or something.)
