### ISSUE TITLE
Milgram theme won't stop playing after first encounter with Berd

### ISSUE THREAD

**Issue by galegosimpatico** [frogatto/frogatto#427]
In "To Nene's House".

A beach music is playing, Milgram theme plays when starting to talk with Berd, keeps playing after dialog is over, but I kinda remember in version 3 it goes back to play the beach theme - similar to how Berd manipulating music works in Zelda Ocarina Of Time.

Can anyone reproduce? Can anyone confirm bug or issue?

**Comment by galegosimpatico** [comment]
Code confirms is bug, `FrogattoChill` is requested when the dialog ends, but it won't play.

**Comment by galegosimpatico** [comment]
Useless trivia:

* when replacing `lib.audio.play_music` for the deprecated `music`, it will crash.
* when replacing the track for some other, it will play.
  * when replacing `lib.audio.play_music` for the deprecated `music`, it won't crash.

**Comment by DDR0** [comment]
Confirmed fixed by #430.
