### ISSUE TITLE
The bomb particle will stay after swallowing the bomb.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#437]
Bug:

![A star from the bomb remains when the bomb is swallowed.](https://user-images.githubusercontent.com/67684800/113388942-6e981880-938f-11eb-8aef-da06c367f276.png)

(This little star is a bomb particle)

Now it shouldn't happen because I remove the particle every time a bomb is on_been_grabbed

Originally reported in [PR 463](https://github.com/frogatto/frogatto/pull/436) by @Cuber01, but we believe this is an indication of something going wrong with our `effects_attache` system and should be fixed there. This bug will track those efforts.

**Comment by rkettering** [comment]
Should be fixed, now.
