### ISSUE TITLE
Verify identity for itch.io project page

### ISSUE THREAD

**Issue by leafo** [frogatto/frogatto#439]
Sorry for the non-standard ticket. We had an account https://lost-pixel.itch.io/ distributing this game, and we originally suspended the page because based on our checks it looks suspicious and we were unable to verify that they were actually a publisher or owner the game who could distribute it.

The account owner is now reaching out to us claiming to be Richard Kettering trying to get it reinstated and we'd like to get proof of ownership by having a committer reply here confirming that this account is indeed associated with the project.

The account is here: https://lost-pixel.itch.io/

Keep in mind this page is currently a 404 since the account is restricted right now.

Edit: For transparency I saw that the account https://github.com/DuckyKing-dev (which previously had the display name set to RKettering) commented saying they confirmed, but then deleted the comment

Thanks

![image](https://user-images.githubusercontent.com/15198/114229101-3dd65700-992c-11eb-909d-1e02a6932a65.png)

![image](https://user-images.githubusercontent.com/15198/114231442-5300b500-992f-11eb-9a09-db22f77619d9.png)

**Comment by DuckyKing-dev** [comment]
Confirmed

**Comment by leafo** [comment]
I was able to determine that they were trying to fraudulently sell the game. Kinda shocked that they went through that much effort to try to lie. Sorry for the noise in this issues tracker.

Here's the full conversation: 

![frogatto-fraud](https://user-images.githubusercontent.com/15198/114232616-f900ef00-9930-11eb-8132-8105163de188.png)

**Comment by rkettering** [comment]
Hey, thanks a ton for getting in touch with us - that's complete fraud, and I really appreciate you reaching out to us.

Whoever this person is is really out of touch, because "Lost Pixel" hasn't been our team name for **almost a decade.**
