### ISSUE TITLE
Our homepage could use a Discord link.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#442]
Main page needs a Discord link, since it's more lively than the forums. Probably on the sidebar above forums.

**Comment by al0fdf** [comment]
> Main page needs a Discord link, since it's more lively than the forums. Probably on the sidebar above forums.

Does it not already?
![image](https://github.com/frogatto/frogatto/assets/104121665/200b6546-6f1e-4051-8c03-760a400a34eb)

**Comment by DDR0** [comment]
I think that's new, or I'm real dumb. Gonna go with A for the sake of my ego.
