### ISSUE TITLE
Website SSL Cert is expired.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#454]
As of 2021-06-52 at 6:00 P.M. PST, our website is down.
![image](https://user-images.githubusercontent.com/862627/123497829-8674e680-d5e4-11eb-8746-aa7aae0479bc.png)

**Comment by al0fdf** [comment]
Website is up. Current certificate is due to expire at `Mon, 21 Nov 2022 20:21:49 GMT`.
