### ISSUE TITLE
We've got some potentially extremely weird behavior with enemies that in frogatto's stomach when he respawns at a save point.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#457]
We're still not sure what's causing it, but it looks like it may involve traveling to a different level.

We've observed two issues - in one, the player attempts to spit out the enemy and his stomach has nothing at all inside it.
The other issue we've observed is an enemy getting spat out correct, but permanently being in an "on_back" state, without (seemingly) any animation progression.

**Comment by DDR0** [comment]
While I have experienced the first of these two errors, I have been absolutely unable to duplicate them in testing here. It seems we will require the steps to reproduce, or a save, before we can fix this.

**Comment by rkettering** [comment]
Fixed in e13ae8317
