### ISSUE TITLE
Liberate proprietary data

### ISSUE THREAD

**Issue by throwaway1037** [frogatto/frogatto#462]
Please may the proprietary data listed in the license file be released under a libre (free as in freedom) license, so as to become libre works as described here: https://freedomdefined.org?

At the moment, some system distributions cannot distribute Frogatto because they have policies against proprietary works.

**Comment by DDR0** [comment]
Hello, Throwaway.

Unfortunately, such a licencing change would cause us some trouble for no benefit. For instance, we do intend to sell the next version of the game fairly soon, and we would like to prevent blatant, for-profit piracy; some of which our older sister game Wesnoth has experienced.

I'm going to close this issue now, but if you'd like to discuss further please feel free to drop by our Discord. :slightly_smiling_face:

**Comment by throwaway1037** [comment]
Hello, @DDR0. 

Thank you for replying so swiftly! 

I'd like to present the case for liberation more fully, if I may: 

In the Free Software Movement and the Free Culture Movement, we firmly believe that all software, and all published works should be free (as in freedom), respectively, ie. all software and published works should have four essential freedoms, which are fully explained at https://gnu.org/philosophy and https://freedomdefined.org, respectively. 

As such, we in the free world have built operating systems from the ground-up to allow 100% freedom for all users, GNU being the first. One such modern operating system distribution which only allows 100% libre works is [Parabola](https://parabola.nu). 

The reason Frogatto is disallowed is because it contains, and is unplayable without, proprietary data. Unfortunately, we can't possibly legally reimplement this data without copyright infringement, unlike software can be reverse engineered and reimplemented, which means that Frogatto is and will be unplayable in the free world until the proprietary works in question enter the public domain and as such become free.

This will happen [70 years after the author's death](https://en.m.wikipedia.org/wiki/List_of_countries%27_copyright_lengths) (in much of the world, for example), and the length of time of copyright is [constantly being extended by lobbyist groups](https://en.m.wikipedia.org/wiki/Copyright_Term_Extension_Act), meaning that for the foreseeable future, copyright may be perpetual by the installment plan, and Frogatto will never become playable in the free world. 

Boring legalities aside, this impacts the free software and free culture communities; we cannot in good conscience play games which are not fully free, which is a tremendous shame. To emphasise, Frogatto is off-limits to us now, and potentially forever. 

Liberation benefits everybody: both the developers, and the community. One benefit is that the community will be able to contribute to the data, thus improving it for everybody, and lessening the burden on the developers, so that their time is freed up to work on more pressing or complex issues. Another benefit is that Frogatto will enter the free world, and can therefore be distributed by many more projects, such as system distros which are 100% libre, and can be listed on the [Libre Game Wiki](https://libregamewiki.org). This would certainly make Frogatto reach a much wider audience, thus driving more people towards contributing. 

Selling any 100% libre software is allowed and supported in the free software and free culture communities; in fact, the right to sell the work is part of the very definitions of free software and free works. 

You used the term ["piracy"](https://www.gnu.org/philosophy/words-to-avoid.html#Piracy), which unfortunately implies that sharing, which is beneficial to society, is ethically equivalent to attacking ships. In fact, a US judge presiding over a trial for copyright infringement recognised that ["piracy", "theft", and "stealing"](https://torrentfreak.com/mpaa-banned-from-using-piracy-and-theft-terms-in-hotfile-trial-131129/) (when used in the context of sharing published works) are smear words, and banned them in the trial. 

I of course assume good faith, and presume that you do not really hold anti-freedom, and anti-sharing opinions. After all, the vast majority of Frogatto is already free, which makes the last necessary chunk of data just so tantalising and saddening that it's proprietary. It would be a shame to succumb to the propaganda of big movie companies, although I understand why repeating such propaganda terms is popular, as I myself have done so, in the past, before I learnt about free culture. 

I presume that your real issue is that others were selling Wesnoth, the developers of which never received any money. This is ethical, as the freedom to sell a work is part of the essential freedoms and very definition of free software and free works, although I understand where you are coming from, since I used to agree with you. 

The freedom to sell, just as we are free to sell any other item in our possession, will not substantially negatively impact your endeavours to sell the game in future. Most people will give money directly to the official project, to support development, whilst a few will sell privately. This is the case for most free works, so it will apply to Frogatto too. Plus, copying and sharing digital data is so ridiculously easy nowadays that if someone really didn't have the money, or really didn't want to pay for a work, it would be trivial to download it from some other place on the internet anyway, and rightly so. Sharing is beneficial to society, and making it legal benefits everyone greatly. 

I'd like to thank you for your invitation to chat, however Discord is unethical because it is proprietary malware; it does not grant users freedom, and their messages are spied on, but to name two issues. Would it be okay if we could continue to discuss this issue here? 

Thank you for reading!
I hope we may reach a resolution of liberation for Frogatto!
:)

**Comment by throwaway1037** [comment]
(Just giving the thread a bump.)

**Comment by throwaway1037** [comment]
Hello, please may somebody respond?

I'd like to add this game to systems which are 100% libre, such as [Parabola](https://parabola.nu), but this is impossible and blocks out entire communities of potential players and contributors to the project, without the game being libre.

**Comment by DDR0** [comment]
See previous response. We are not doing this; if you want our game, you
have to use our stuff. Sorry to be brief, but we have a lot of things to do
and not a lot of people to do it with.

**Comment by throwaway1037** [comment]
> We are not doing this; if you want our game, you have to use our stuff.

The game isn't "yours", rather you *hold* the copyright over it; each player owns his or her own copy, but are restricted from having freedom over it because it's proprietary.
This is an injustice because each player cannot control his or her own property.

I humbly ask for the last time that you may please liberate the game; since you are a proprietor I have no option to obtain freedom for this game and its players than to but to beg and grovel at your feet for it.
It would be a tremendous injustice to continue to treat your players unethically, which is a shame because it doesn't have to be this way.

**Comment by AI0867** [comment]
> The game isn't "yours"

> This is an injustice [...]

> [...] tremendous injustice to continue to treat your players unethically [...]

> I humbly ask for the last time [...]

If you want to to ask the people[^1] who created this game, and already contributed a lot of their time and work to open source, to give up the rights that afford them the bit of exclusivity that enables them to make some money from the tremendous amount of effort they've invested, the very least you can do is be polite and actually sign your name to the requests rather than using throwaway accounts.

Right now your posts are indistinguishable from those of a troll, so personally, I'm blocking you.

[^1]: I don't include myself in this set. I just help out a bit from time to time.

**Comment by throwaway1037** [comment]
You use the following propaganda terms, on which your argument is predicated:
- ["Create"](https://gnu.org/philosophy/words-to-avoid.html#Creator): this term seeks to give copyright holders inflated and superior morality in order to justify harsh copyright regimes and proprietary works.
They authored they game, and they have an ethical duty to respect the freedom of its players.
- ["Open source"](https://gnu.org/philosophy/words-to-avoid.html#Open): this term is used to promote so-called "openness" merely as a desirable feature instead of freedom as an ethical imperative.
Moreover, [open source misses the point of freedom](https://gnu.org/philosophy/open-source-misses-the-point.html).
- ["give up the right"](https://gnu.org/philosophy/words-to-avoid.html#Protection) implies that they should have the right to restrict people, which they shouldn't.
Respecting freedom is an ethical imperative.
They should not have "exclusivity" over the freedom of others.

You word your message as if they're hard done by and deserve to restrict people in order to make money.
This is ludicrous.
They can make just as much money whilst simultaneously respecting people's freedom; it wouldn't cause them any trouble at all.

I am being polite; if begging and grovelling for freedom is seen as "trolling", then that just shows how far gone our society is at the moment.
I use a throwaway account because I don't want to give MS data about me; this does not devalue my argument in any way.
Moreover, you won't be able to correct your mistakes I've pointed out because you blocked me; your loss.
