### ISSUE TITLE
Reproducible crash on `blind-alley.cfg`

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#505]
Possibly related to:
https://github.com/frogatto/frogatto/issues/444

If I load the saved game on `blind_alley.cfg`, and press the "Return to Titlescreen" button, then I get a full anura crash with the following stack trace:
```
#0    0x0000000101277e00 in typeinfo for boost::exception_detail::bad_alloc_ ()
#1    0x000000010067f656 in LevelRunner::play_level() at /Users/admin/Public/anura/src/level_runner.cpp:904
#2    0x00000001006b4430 in main at /Users/admin/Public/anura/src/main.cpp:1247
#3    0x00007fff7c9eb015 in start ()
#4    0x00007fff7c9eb015 in start ()
```

[save.cfg.zip](https://github.com/frogatto/frogatto/files/7776350/save.cfg.zip)

**Comment by DDR0** [comment]
There is a second crash, probably related to the first, where the level dies while playing it. To reproduce, open the level in the editor and zoom out all the way.

``
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348462016) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348462016) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737348462016, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7842476 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#4  0x0000555556209ac6 in game_logic::(anonymous namespace)::AssertExpression::execute (this=<optimized out>, variables=...) at src/formula.cpp:3428
#5  0x0000555556204ba6 in game_logic::FormulaExpression::evaluate (variables=..., this=0x5555665ff7b0) at src/formula_function.hpp:83
#6  game_logic::Formula::execute (this=this@entry=0x5555665fa9b0, variables=...) at src/formula.cpp:5333
#7  0x0000555556036c04 in CustomObject::handleEventInternal (this=0x555566609040, event=433, context=<optimized out>, executeCommands_now=false) at src/custom_object.cpp:5483
#8  0x0000555556002b11 in detect_user_collisions (lvl=...) at src/collision_utils.cpp:828
#9  0x00005555564438f7 in Level::do_processing (this=0x55555a3ea1d0) at src/level.cpp:2785
#10 0x00005555564442e1 in Level::process (this=0x55555a3ea1d0) at src/level.cpp:2654
#11 0x000055555648a89f in LevelRunner::play_cycle (this=0x7fffffffd350) at src/level_runner.cpp:1739
#12 0x000055555648f817 in LevelRunner::play_level (this=this@entry=0x7fffffffd350) at src/level_runner.cpp:896
#13 0x0000555555c6bccd in main (argcount=<optimized out>, argvec=<optimized out>) at src/main.cpp:1259
```

Based on frame 8, it seems to be collision-related. Poking around, I get another backtrace trying to access a value in frame 4, `print a->str()`. Something is failing a `px != 0` assert there in frame 5 of the resulting backtrace.

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348462016) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348462016) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737348462016, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7842476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff782871b in __assert_fail_base (fmt=0x7ffff79dd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555556f709e5 "px != 0", file=0x555556f70858 "./vcpkg_installed/x64-linux/include/boost/smart_ptr/intrusive_ptr.hpp", line=199, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff7839e96 in __GI___assert_fail (assertion=0x555556f709e5 "px != 0", file=0x555556f70858 "./vcpkg_installed/x64-linux/include/boost/smart_ptr/intrusive_ptr.hpp", line=199, function=0x555556f868e8 "T* boost::intrusive_ptr<T>::operator->() const [with T = game_logic::FormulaExpression]") at ./assert/assert.c:101
#7  0x0000555556268305 in boost::intrusive_ptr<game_logic::FormulaExpression>::operator-> (this=<optimized out>) at ./vcpkg_installed/x64-linux/include/boost/smart_ptr/intrusive_ptr.hpp:199
#8  <function called from gdb>
#9  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348462016) at ./nptl/pthread_kill.c:44
#10 __pthread_kill_internal (signo=6, threadid=140737348462016) at ./nptl/pthread_kill.c:78
#11 __GI___pthread_kill (threadid=140737348462016, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#12 0x00007ffff7842476 in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#13 0x0000555556209ac6 in game_logic::(anonymous namespace)::AssertExpression::execute (this=<optimized out>, variables=...) at src/formula.cpp:3428
#14 0x0000555556204ba6 in game_logic::FormulaExpression::evaluate (variables=..., this=0x5555665ff7b0) at src/formula_function.hpp:83
#15 game_logic::Formula::execute (this=this@entry=0x5555665fa9b0, variables=...) at src/formula.cpp:5333
#16 0x0000555556036c04 in CustomObject::handleEventInternal (this=0x555566609040, event=433, context=<optimized out>, executeCommands_now=false) at src/custom_object.cpp:5483
#17 0x0000555556002b11 in detect_user_collisions (lvl=...) at src/collision_utils.cpp:828
#18 0x00005555564438f7 in Level::do_processing (this=0x55555a3ea1d0) at src/level.cpp:2785
#19 0x00005555564442e1 in Level::process (this=0x55555a3ea1d0) at src/level.cpp:2654
#20 0x000055555648a89f in LevelRunner::play_cycle (this=0x7fffffffd350) at src/level_runner.cpp:1739
#21 0x000055555648f817 in LevelRunner::play_level (this=this@entry=0x7fffffffd350) at src/level_runner.cpp:896
#22 0x0000555555c6bccd in main (argcount=<optimized out>, argvec=<optimized out>) at src/main.cpp:1259
```

This is probably an assert the level editor should catch.

**Comment by DDR0** [comment]
I've filed a bug for the underlying crash, and since #641 fixes this bug.
