### ISSUE TITLE
shadow shader takes into account 1 z-layer behind it as well as own layer.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#509]
Jetrel — Today at 02:14
@DDR  weird bug for us to look at:   as soon as I added a shadow effect to prospera's workshop, the foreground items ended up in this ghostly "additive blending" look:
![image](https://user-images.githubusercontent.com/862627/147809066-de06fe6e-3e6b-43c4-a2e7-d24eb00f8c51.png)
(ed note.: See bottom-left items on table.)

DDR — Today at 22:36
OK, so I've had a look at this.

1. Removing the shadow shader fixes the problem.
2. Modifying the shadow shader confirms it's definitely affecting the item layer.
3. The items are at z200 (in_front_of_parallax_objects). The shadow is at z300 (shadow_overlay).

Any value other than +-0 breaks shadows entirely, ie, nothing in the affected layers draws to screen. (This includes the foreground items.)
begin_zorder: lib.zorder.get('shadow_overlay')+0,
end_zorder: lib.zorder.get('shadow_overlay')+0

DDR — Today at 23:04
shaders.cfg:shadow doesn't have zorder in it; none of the shaders there do. I don't think it's supported in that file, it really does just seem a collection of vertex/fragment shaders.
shadow_effect_controller.cfg:78 sets the begin and end zorder of the shadow; changing these values does change the zorder of the shadow. The value is being read out of zorder.cfg correctly as 300.

Jetrel — Today at 23:05
Okay, welllll then it might actually be an engine bug.

DDR — Today at 23:05
Changing the value in zorder.cfg from 300 to, say, 150 fixes the bug. Of course, the items are in front of the shadow then, and something else is erroneously behind it. Disabling the shader fixes things as expected. It _must_ not be that.
The powerups correctly debug as z-index 200.

**Comment by DDR0** [comment]
DDR — Today at 23:17
Possible hot-fix: Putting one low-or-no-visibility item on a layer behind the shader to absorb the damage.
Note: This seems entirely related to relative layer order, not layer order numerical value.

**Comment by rkettering** [comment]
Fixed in:  https://github.com/anura-engine/anura/commit/a484a10f1b512805b55ec78dbd6498f09c71882a
