### ISSUE TITLE
port the energyshot and homingshot particles into the legacy_particle_attache

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#513]
Right now they're very badly centered on the player's shots.

**Comment by rkettering** [comment]
Fixed in 97c6ff3dbb6f40f05eefa85472e173e8925ac81a ff28b2da022a532a010b4817e369b4d428239da6 71135690d037c532016f9e12dc8a2a2c91fce2c4 9d65c8a12b10fe4ea5245524a48635ab11734600

**Comment by DDR0** [comment]
I meant 534. :p
