### ISSUE TITLE
Keys can go through red/blue puzzle blocks, resulting in possible softlocks

### ISSUE THREAD

**Issue by Cuber01** [frogatto/frogatto#517]
Entire discussion:
https://discord.com/channels/225816341737766912/920412269718953994/934539982926913606

![image](https://user-images.githubusercontent.com/67684800/150654114-bd5f4ba1-94ca-4e28-8e94-53c5f395e534.png)

**Comment by rkettering** [comment]
Hopefully fixing this via:  3b7f84e50
