### ISSUE TITLE
Fullscreen pause menu text misaligned.

### ISSUE THREAD

**Issue by Cuber01** [frogatto/frogatto#518]
Full discussion:
https://discord.com/channels/225816341737766912/920412269718953994/934409553959874570

![image](https://user-images.githubusercontent.com/67684800/150654225-e53dd101-db28-4b77-807a-f37b16787b5c.png)
![image](https://user-images.githubusercontent.com/67684800/150654228-50ad77df-2245-4b80-96ab-ddf3c048290e.png)

**Comment by DDR0** [comment]
Confirmed. Bit of a mess, really. 
![image](https://user-images.githubusercontent.com/862627/151721217-814e0dae-7464-481e-bc55-59d1c7a66eb3.png)

**Comment by DDR0** [comment]
There are two issues at play here, the text being misaligned on the main menu and the whole game field being in the bottom-left corner. I believe the latter to be fixed in commit 86b96a90d. :slightly_smiling_face:

**Comment by Vultraz** [comment]
Can confirm the text alignment issue is still present, but the game renders fine in fullscreen.

**Comment by DDR0** [comment]
May be related to https://github.com/anura-engine/anura/issues/183.

**Comment by DDR0** [comment]
May be tangentially related to https://github.com/frogatto/frogatto/issues/575.

**Comment by DDR0** [comment]
This is fixed now, I think. I _think_ it was something to do with a change in behaviour of one of our libraries where a 3D structure stopped getting zero-initialized in an update? :thinking: It was a while back now.
