### ISSUE TITLE
HRTF 3D positional audio support

### ISSUE THREAD

**Issue by jan-kleks** [frogatto/frogatto#522]
If implemented well, 3D positional audio can greatly improve immersion (even for a 2D game). Check out for instance this video with headphones: [Duke Nukem: Manhattan Project w/ 3D spatial sound 🎧 (OpenAL Soft HRTF audio)](https://www.youtube.com/watch?v=KfLbO_xHF0Y)

Please consider supporting this in the future.

Regards

**Comment by DDR0** [comment]
We do have some support for better positioning of sound in our upcoming
release. If you'd like to improve on it, we are always open to patches as
well. :)
