### ISSUE TITLE
Key respawn cutscene seems to soft-lock the player if they die during it.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#537]
> A beholder(the eye-like things that shoot fireballs when they see you) hit me, and knocked a key out of my mouth into the pit. I falled into the pit while the key-respawn cutscene was playing, now I cannot move by pressing any of the keys. I was in the Musty Mine when this happened(I can also quit to title screen, but still cannot move 🙂 )

**Comment by Vultraz** [comment]
I just came across this in the Central House dungeon.

**Comment by rkettering** [comment]
This might be an engine issue, from my investigation of it last night.   DDR and I have a hunch that after you die, the control-lock being referenced may be the one from the **prior** player object.

**Comment by rkettering** [comment]
Repro case:  level:  `grassy-path.cfg`.    Simply talk to an npc (one of the question marks), enter the `esc` menu, and `Return to Titlescreen` before the player stops walking.

**Comment by rkettering** [comment]
We determined that the level (or possibly the player?) actually isn't correctly getting deallocated after the player dies.   This has been fixed enough in 07832e935 to kick it over to the "would be nice" list, but we really ought to do a proper fix for the issue.

**Comment by al0fdf** [comment]
Presumably staying open until a proper fix is found?
