### ISSUE TITLE
Attack selector can show up during dialog

### ISSUE THREAD

**Issue by Vultraz** [frogatto/frogatto#541]
Pressing Q during a dialog sequence causes this to happen:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/3558659/158004923-70b4bb98-6d49-400c-9c97-c44212a92f44.png">

Likely related to #530.

**Comment by rkettering** [comment]
Fixed in b2f40eacaae3bb3d801703fed90e94f0a3f91101 and 0ef48db4917f3c209efdd480b9bae416fa22a4e0
