### ISSUE TITLE
The Iralchtahne of Issikoria is super-vulnerable to acorns.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#543]
Is one single squirrel acorn supposed to totally obliterate the Iralchtahne?
I brought a squirrel down from Foreboding Forest, thinking of speedrunning the Iralchtahne fight.
It was more of a speedrun than I thought, as one hit from the acorn made it die.
—[LaserCat in #feedback-and-testing](https://discord.com/channels/225816341737766912/920412269718953994/952687086148939876)

**Comment by al0fdf** [comment]
Only applies to acorns thrown by squirrels.

> Is one single squirrel acorn supposed to totally obliterate the Iralchtahne? I brought a squirrel down from Foreboding Forest, thinking of speedrunning the Iralchtahne fight. It was more of a speedrun than I thought, as one hit from the acorn made it die. —[LaserCat in #feedback-and-testing](https://discord.com/channels/225816341737766912/920412269718953994/952687086148939876)

**Comment by al0fdf** [comment]
Solved by 885437200da9f00e296950f6b18730ff64ec7497
