### ISSUE TITLE
UI indicates super-power is ready for use after swallowing enemy after picking up fire talisman at Nene's, but ability does not seem triggerable.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#545]
I understand that my mouth is full, but when trying to use something by using the tongue key, it just switches to the tongue and spits it out.
—[al0f in #general](https://discord.com/channels/225816341737766912/225816341737766912/952843264891965460)

I have had a poke at this myself and it seems that a further unlock is needed to do this. The UI **should not** suggest it an action if it is not available. The solution for this is probably to suppress the ability-switching behaviour until supers are unlocked.

**Comment by rkettering** [comment]
Fixed in 1eb8e0a894644a5f8c68ef004f1ed83058c1a5cd 9b4883648e88f807ab2ffc0ba127cb73394abad5 72313fcc575deb0048ee4626adf34c63b3f8194a 7086f23a294a2934022afaa9db2d426de20eedd2
