### ISSUE TITLE
crevice village house 1 door broken after liberation

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#550]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/863312/163092200-9027508f-48c6-4149-be4b-4933fc978545.png">
<img width="451" alt="image" src="https://user-images.githubusercontent.com/863312/163092213-76982786-d364-401b-9207-36f15514942f.png">

**Comment by DDR0** [comment]
Duplicated by https://github.com/frogatto/frogatto/issues/547.
