### ISSUE TITLE
Need to provide a list of valid object types present in the game

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#579]
We've had a few problems over the years where we need to procedurally generate an object type type  such as `object('${me.type}.thrown', x, y, 1)`, but we don't know if this is safe to do, because we don't know if this object type exists in the game.   Related to this issue:  https://github.com/frogatto/frogatto/issues/493

It would be awfully nice to be able to just query this as a list of valid objects - of type `[string]`.

**Comment by DDR0** [comment]
Should be fixed in commit 38404d2a5, albeit as a function to query said list instead of a list.
