### ISSUE TITLE
Charged fire breath attack randomly asserts

### ISSUE THREAD

**Issue by al0fdf** [frogatto/frogatto#598]
![image](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/kyPcxocuSPPjbyYvHwnDdRBT)
[log.txt](https://github.com/frogatto/frogatto/files/8984454/log.txt)
In all crashes like this, I was damaged by an enemy when I had the charged fire breath selected.

Load this save: [save2.txt](https://github.com/frogatto/frogatto/files/8988295/save2.txt)
Then fall down through the platform and jump back up, making sure to get hit by that enemy. 

Even more prominent when using the fire attack in the cave ambush.

**Comment by rkettering** [comment]
Fixed in 042b25406
