### ISSUE TITLE
It Mortimer's house, after Stonepipe Bridge, Mortimer is sometimes mute.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#627]
al0f [reports](https://discord.com/channels/225816341737766912/920412269718953994/994817797500698725), "Half the time after completing Stonepipe Bridge, I can't seem to talk to Mortimer after entering his house. After a save reload the game is like "What are you talking about? You were always able to talk with Mortimer"."

**Comment by rkettering** [comment]
Fixed in:  https://github.com/frogatto/frogatto/commit/8d8ec4f71f4e997e2aed4d75e88a00c83932f347
