### ISSUE TITLE
Money counter not appearing in Chopple's Shop.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#628]
al0f [reports](https://discord.com/channels/225816341737766912/920412269718953994/994822991126990869), "The money counter is not appearing..."
![image](https://user-images.githubusercontent.com/862627/178132314-a21e1fe3-b663-43ba-84a5-3cf0f3a34527.png)

**Comment by al0fdf** [comment]
The command for this would be `set(gold.last_changed_coins, gold.cycle) where gold = filter(level.player.spawned_children, value is obj hud_gold_display)[0]`, but there should definitely be a flag to show the gold counter without a timeout.
