### ISSUE TITLE
bug with attaches upon using moth bomb

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#634]
> During this boss fight, after using a bomb I got in the stomach from the previous map. Bats drop that kind of bomb.

![image](https://user-images.githubusercontent.com/863312/181900032-fad87688-107e-4ee3-987b-bb7e55659455.png)

![image](https://user-images.githubusercontent.com/863312/181900155-b4ef929a-5e2c-4234-9f1c-486c595aebe4.png)

**Comment by DDR0** [comment]
Changing `value.possibly_restore_parent_reference` to `if(value, value.possibly_restore_parent_reference)` in transient_object.cfg, we get:
```
CRITICAL: custom_object.cpp:771 ASSERTION FAILED: Object moth_bomber_bomb is invalid, property _effects_attaches expected to be [obj effects_attache] but found [null,null,"@eval deserialize('d5d2234b72e642c8bd6b514b199c32d5')","@eval deserialize('4527c06b32874bf9aa5a8ce63ed98d4c')"] which is of type [null,null,obj legacy_particle_attache,obj light_source_attache,] 0
```
