### ISSUE TITLE
The elder's post-fight cutscene yields no heart when skipped at the right moment.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#635]
> Fight ~~LaserCat~~ Ralph, then wait for him to walk out the door. Once the heart capsule appears, skip the cutscene(Esc). You entirely skip the heart.
> This does not happen when you skip it before Ralph walks out the door.
– al0f

![image](https://user-images.githubusercontent.com/862627/188300196-3627e2be-47e2-4592-8cfa-5b5e8b80c118.png)

**Comment by al0fdf** [comment]
It is now no longer possible to skip at the right moment because now the cutscene only starts when the Elder walks out of his secret passage, anything before that is not considered a cutscene and is unable to be skipped.
