### ISSUE TITLE
Mushroom boss asserts on defeat once again

### ISSUE THREAD

**Issue by lasercatto** [frogatto/frogatto#651]
Separate error from https://github.com/frogatto/frogatto/issues/533

![image](https://user-images.githubusercontent.com/104042244/217692804-0e609e7b-a6b4-442a-b80a-cf2397339c19.png)

**Comment by rkettering** [comment]
Fixed in https://github.com/frogatto/frogatto/commit/ad1a2ca09120e0098f65dbc067e0bcae22cdcfc9
