### ISSUE TITLE
Create `data/pause-menu.cfg`

### ISSUE THREAD

**Issue by al0fdf** [frogatto/frogatto#689]
In anura's `pause_game_dialog.cpp` I see the following lines:
```
variant v;
	try {
		v = json::parse_from_file("data/pause-menu.cfg");
		ASSERT_LOG(v.is_map(), "\"data/pause-menu.cfg\" found but isn't a map.");
		variant button_color_scheme = v["button_color_scheme"];
```

I think this is the code to load options from a `pause-menu.cfg` in the module. This should be created in the frogatto module so that the main pause menu can be read from the frogatto module, not the engine.

**Comment by DDR0** [comment]
Yeah; alas, I think it's mostly used for Argentum Age theming right now.
