### ISSUE TITLE
update credits

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#692]
Add Akhiros, Cubey, LaserCat, Al0f, and probably give a shout-out to Levie for past assistance and... uh... who was helping out with the store art and didn't we actually pay someone to do a few scutwork inbetween animation frames for us a while back?

**Comment by al0fdf** [comment]
Where my role was suggested to be "Does all the annoying little quality of life fixes that no-one really wants to do or can be bothered with or they're not of a high enough level if importance, quite often while he is meant to be focusing on something else" or "notorious bug fixer" or "senior engineer".

**Comment by DDR0** [comment]
Hey. That's how I became a senior engineer!

**Comment by al0fdf** [comment]
Possibly with a secondary title of "Squirrel Tester".

**Comment by al0fdf** [comment]
Solved by 1cdcccbbfc561eec66bc36e43e4aec58ce5cc114

**Comment by al0fdf** [comment]
"[Added **but did not wire in** several new triggers in the credits cutscene](https://github.com/frogatto/frogatto/commit/2d2460bb022dacc7eeefcc98eb97e3dc393bae50)"

**Comment by al0fdf** [comment]
Fixed in 1cdcccb
